export const SET_APY = "SET_APY";
export const SET_SOL_USD = "SET_SOL_USD";
export const SET_INVESTMENT_AMOUNT = "SET_INVESTMENT_AMOUNT";
export const SET_INVESTMENT_TIME = "SET_INVESTMENT_TIME";
export const SET_INVESTMENT_PERIOD = "SET_INVESTMENT_PERIOD";
export const SET_TOTAL_AMOUNT = "SET_TOTAL_AMOUNT";
export const SET_TOTAL_MONEY = "SET_TOTAL_MONEY";